apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-sdk
  name: node-sdk
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    name: node-sdk