apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-env-config
data:
  PORT: "8000"
  ORG_MSP: Org1MSP
  CHANNEL_NAME: samplechannel
  CHAINCODE_NAME: fabricSmartContractGo

---
apiVersion: v1
kind: Secret
metadata:
  name: sdk-secret
type: Opaque
stringData:
  CA_ADMIN_USERID: admin
  CA_ADMIN_PASSWORD: <REPLACE_ME>
  ORG_USER_ID: fabricUser
  ORG_USER_SECRET: <REPLACE_ME>