apiVersion: v1
kind: ConfigMap
metadata:
  name: sdk-env-config
data:
  PORT: "8000"
  ORG_MSP: Org1MSP
  CHANNEL_NAME: samplechannel
  CHAINCODE_NAME: fabricSmartContractGo
  RE_ENROLL_USER_ID: "false"
  config.json: |-
      {
      "request-timeout" : 40000,
      "tcert-batch-size" : 10,
      "crypto-hash-algo": "SHA2",
      "crypto-keysize": 256,
      "crypto-hsm": false,
      "connection-timeout": 40000
      }

---
apiVersion: v1
kind: Secret
metadata:
  name: sdk-secret
type: Opaque
stringData:
  CA_ADMIN_USERID: admin
  CA_ADMIN_PASSWORD: <REPLACE_ME>
  ORG_USER_ID: fabricUser
  ORG_USER_SECRET: <REPLACE_ME>