apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: node-sdk
  template:
    metadata:
      labels:
        name: node-sdk
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker2
      volumes:
        - name: fabric-nfs
          persistentVolumeClaim:
            claimName: fabric-pvc-nfs
        - name: ca-client-config
          configMap:
            name: sdk-env-config
            items:
              - key: config.json
                path: config.json
                mode: 0544

      containers:
        - name: node-sdk
          stdin: true
          tty: true
          env:
            - name: DEBUG
              value: "fabric-network:*"
          image: vikashftw/fabric-node-sdk:1.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: sdk-env-config
            - secretRef:
                name: sdk-secret
          volumeMounts:
            - name: fabric-nfs
              mountPath: /usr/src/app/connection-profile
              subPath: connection-profile
            - name: fabric-nfs
              mountPath: /usr/src/app/wallet
              subPath: wallet
            - name: fabric-nfs
              mountPath: /usr/src/app/logs
              subPath: logs
            - name: ca-client-config
              mountPath: /usr/src/app/config.json
              subPath: config.json